version: '3.8'
services:
  db:
    image: postgres:15.0-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    networks:
      - default
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo"]
      interval: 2s
      timeout: 30s
      retries: 5

networks:
  default:

volumes:
  escapedata:
